title = "PACKAGE-NAME"

gitSourceBranch = "main"
changelog = true

[docusaurus]
onBrokenLinks = "warn"
onBrokenAnchors = "ignore"
onBrokenMarkdownLinks = "warn"

[footer]
style = "dark"
copyright = "Copyright Â© 2025 Its a bit random. Built with Moonwave and Docusaurus"